version: "3.9"

services:
    jio_savan_music_downloader:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jio_savan_music_downloader
        ports:
            - "7860:7860"
        volumes:
            - .:/app
        environment:
            - PYTHONUNBUFFERED=1
        command: >
            jio_savan_music_downloader
